2019-09-25 23:09:04: "Starting server on port 3222 and PID 18436..."
2019-09-25 23:22:10: "Starting server on port 3222 and PID 19006..."
2019-09-25 23:22:10: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-25 23:22:11: "Error: Invalid link: photo.jpg:
Error: Invalid link: photo.jpg:
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:107:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:57:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:77:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:67:33"
2019-09-25 23:23:13: "Starting server on port 3222 and PID 19144..."
2019-09-25 23:23:13: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-25 23:23:14: "Error: Invalid link: photo.jpg:
Error: Invalid link: photo.jpg:
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:108:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:57:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:77:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:67:33"
2019-09-25 23:26:16: "Starting server on port 3222 and PID 19281..."
2019-09-25 23:26:16: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-25 23:26:17: "Error: Invalid link: photo.jpg:
Error: Invalid link: photo.jpg:
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:99:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:77:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:67:33"
2019-09-25 23:27:31: "Starting server on port 3222 and PID 19422..."
2019-09-25 23:27:31: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-25 23:27:32: "Error: Invalid link: photo.jpg:
Error: Invalid link: photo.jpg:
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:77:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:67:33"
2019-09-25 23:29:05: "Starting server on port 3222 and PID 19586..."
2019-09-25 23:29:05: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-25 23:29:05: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:77:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:67:33"
2019-09-25 23:30:05: "Starting server on port 3222 and PID 19723..."
2019-09-25 23:30:05: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-25 23:30:06: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:77:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:67:33"
2019-09-25 23:31:13: "Starting server on port 3222 and PID 19860..."
2019-09-25 23:31:13: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-25 23:31:14: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:78:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:68:33"
2019-09-25 23:39:33: "Starting server on port 3222 and PID 20052..."
2019-09-25 23:39:33: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-25 23:39:34: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:78:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:68:33"
2019-09-25 23:40:11: "Starting server on port 3222 and PID 20189..."
2019-09-25 23:40:11: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-25 23:40:11: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:78:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:68:33"
2019-09-25 23:41:20: "Starting server on port 3222 and PID 20326..."
2019-09-25 23:41:20: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-25 23:41:21: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:78:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:68:33"
2019-09-25 23:43:35: "Starting server on port 3222 and PID 20467..."
2019-09-25 23:43:35: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-25 23:43:36: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:78:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:68:33"
2019-09-25 23:46:40: "Starting server on port 3222 and PID 20654..."
2019-09-25 23:46:41: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:78:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:68:33"
2019-09-25 23:46:58: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:78:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:68:33"
2019-09-25 23:47:18: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:78:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:68:33"
2019-09-25 23:47:55: "Starting server on port 3222 and PID 20707..."
2019-09-25 23:48:03: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:78:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:68:33"
2019-09-25 23:48:05: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:78:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:68:33"
2019-09-25 23:51:46: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:78:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:68:33"
2019-09-25 23:51:55: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:78:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:68:33"
2019-09-25 23:52:01: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:78:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:68:33"
2019-09-25 23:55:52: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:78:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:68:33"
2019-09-25 23:55:56: "Error: Invalid link: content
Error: Invalid link: content
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at Object.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:93:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:15:12)
    at Object.exec (/mnt/c/Users/laurent/src/joplin/Server/dist/app/routes/api/files.js:56:16)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:78:50
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:33:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:14:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:4:12)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/app.js:68:33"
2019-09-26 00:19:43: "Starting server on port 3222 and PID 21486..."
2019-09-26 00:19:43: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-26 00:20:20: "BadRequestError: request aborted
Code: ECONNABORTED
BadRequestError: request aborted
    at IncomingMessage.onAborted (/mnt/c/Users/laurent/src/joplin/Server/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:209:13)
    at abortIncoming (_http_server.js:492:9)
    at socketOnEnd (_http_server.js:508:5)
    at Socket.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
2019-09-26 00:21:05: "Error: insert into `sessions` (`created_time`, `id`, `updated_time`, `user_id`) values (1569453665609, 'RKknSph1Axu24GS77wG8n4', 1569453665609, 'qDHz48WYLFWRl5ECqojjSR') - SQLITE_READONLY: attempt to write a readonly database
Code: SQLITE_READONLY
Error: SQLITE_READONLY: attempt to write a readonly database
    at createQueryBuilder (/mnt/c/Users/laurent/src/joplin/Server/node_modules/knex/lib/util/make-knex.js:257:26)
    at SessionModel.knex (/mnt/c/Users/laurent/src/joplin/Server/node_modules/knex/lib/util/make-knex.js:13:12)
    at SessionModel.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/BaseModel.js:191:51)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/BaseModel.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/BaseModel.js:25:53)
    at fulfilled (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/BaseModel.js:16:58)"
2019-09-26 00:21:06: "Starting server on port 3222 and PID 21623..."
2019-09-26 00:21:06: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-26 00:21:37: "BadRequestError: request aborted
Code: ECONNABORTED
BadRequestError: request aborted
    at IncomingMessage.onAborted (/mnt/c/Users/laurent/src/joplin/Server/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:209:13)
    at abortIncoming (_http_server.js:492:9)
    at socketOnEnd (_http_server.js:508:5)
    at Socket.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
2019-09-26 00:22:05: "Error: insert into `sessions` (`created_time`, `id`, `updated_time`, `user_id`) values (1569453725563, 'PSGFmHTtTH04TK7ntZNdDF', 1569453725563, 'qDHz48WYLFWRl5ECqojjSR') - SQLITE_READONLY: attempt to write a readonly database
Code: SQLITE_READONLY
Error: SQLITE_READONLY: attempt to write a readonly database
    at createQueryBuilder (/mnt/c/Users/laurent/src/joplin/Server/node_modules/knex/lib/util/make-knex.js:257:26)
    at SessionModel.knex (/mnt/c/Users/laurent/src/joplin/Server/node_modules/knex/lib/util/make-knex.js:13:12)
    at SessionModel.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/BaseModel.js:191:51)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/BaseModel.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/BaseModel.js:25:53)
    at fulfilled (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/BaseModel.js:16:58)"
2019-09-26 00:22:06: "Starting server on port 3222 and PID 21752..."
2019-09-26 00:22:06: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-26 00:22:13: "BadRequestError: request aborted
Code: ECONNABORTED
BadRequestError: request aborted
    at IncomingMessage.onAborted (/mnt/c/Users/laurent/src/joplin/Server/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:209:13)
    at abortIncoming (_http_server.js:492:9)
    at socketOnEnd (_http_server.js:508:5)
    at Socket.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
2019-09-26 00:23:00: "Starting server on port 3222 and PID 21906..."
2019-09-26 00:23:00: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-26 00:23:01: "Error: file not found: "photo.jpg" on parent "NUx0N6YGTBW4UvCqgbklAw"
Error: file not found: "photo.jpg" on parent "NUx0N6YGTBW4UvCqgbklAw"
    at ErrorNotFound.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorNotFound (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:44:28)
    at FileModel.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/FileModel.js:329:35)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/FileModel.js:57:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/FileModel.js:38:53)
    at fulfilled (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/FileModel.js:29:58)"
2019-09-26 00:29:01: "Starting server on port 3222 and PID 22043..."
2019-09-26 00:29:01: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-26 00:29:02: "Error: name cannot be empty
Error: name cannot be empty
    at ErrorUnprocessableEntity.ApiError [as constructor] (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:22:28)
    at new ErrorUnprocessableEntity (/mnt/c/Users/laurent/src/joplin/Server/dist/app/utils/errors.js:77:28)
    at FileModel.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/FileModel.js:177:39)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/FileModel.js:57:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/FileModel.js:38:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/models/FileModel.js:32:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/FileModel.js:28:12)
    at FileModel.validate (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/FileModel.js:169:16)
    at FileModel.<anonymous> (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/BaseModel.js:185:51)
    at step (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/BaseModel.js:44:23)
    at Object.next (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/BaseModel.js:25:53)
    at /mnt/c/Users/laurent/src/joplin/Server/dist/app/models/BaseModel.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/BaseModel.js:15:12)
    at FileModel.BaseModel.save (/mnt/c/Users/laurent/src/joplin/Server/dist/app/models/BaseModel.js:165:16)"
2019-09-26 00:30:14: "Starting server on port 3222 and PID 22180..."
2019-09-26 00:30:14: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-26 00:31:56: "Starting server on port 3222 and PID 22355..."
2019-09-26 00:31:56: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
2019-09-26 00:37:27: "Starting server on port 3222 and PID 22492..."
2019-09-26 00:37:27: "Writing PID to /mnt/c/Users/laurent/src/joplin/Server/dist/tests/../../test.pid..."
